-- ============================================
-- LIMPIAR TABLAS (PostgreSQL)
-- ============================================
TRUNCATE TABLE job_requirements CASCADE;
TRUNCATE TABLE job_vacancies CASCADE;
TRUNCATE TABLE job_positions CASCADE;
TRUNCATE TABLE companies CASCADE;
TRUNCATE TABLE job_events CASCADE;
TRUNCATE TABLE job_missions CASCADE;

-- Reiniciar secuencias
ALTER SEQUENCE IF EXISTS job_vacancies_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS job_requirements_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS job_events_id_seq RESTART WITH 1;
ALTER SEQUENCE IF EXISTS job_missions_id_seq RESTART WITH 1;

-- ============================================
-- 1. COMPANIES
-- ============================================
INSERT INTO companies (id, name, category, description, location, website, logo_url, contact_email, phone, active, employees_count, founded_year, remote_friendly, internship_available) VALUES
(1, 'TechCorp Solutions', 'TECHNOLOGY', 'Empresa líder en desarrollo de software y soluciones tecnológicas.', 'Madrid, España', 'https://techcorp.es', 'https://example.com/logos/techcorp.png', 'rrhh@techcorp.es', '+34 912 345 678', true, 500, 2010, true, true),
(2, 'DataMind Analytics', 'TECHNOLOGY', 'Consultoría en Big Data e inteligencia artificial.', 'Barcelona, España', 'https://datamind.es', 'https://example.com/logos/datamind.png', 'jobs@datamind.es', '+34 932 345 678', true, 200, 2015, true, true),
(3, 'HealthPlus Medical', 'HEALTH', 'Red de centros médicos y servicios de telemedicina.', 'Valencia, España', 'https://healthplus.es', 'https://example.com/logos/healthplus.png', 'empleo@healthplus.es', '+34 963 456 789', true, 800, 2005, false, true),
(4, 'Wellness Care', 'HEALTH', 'Clínicas de fisioterapia y centros de bienestar.', 'Sevilla, España', 'https://wellnesscare.es', 'https://example.com/logos/wellness.png', 'rrhh@wellnesscare.es', '+34 954 567 890', true, 150, 2012, false, true),
(5, 'Global Finance Group', 'FINANCE', 'Servicios financieros y asesoría de inversiones.', 'Madrid, España', 'https://globalfinance.es', 'https://example.com/logos/globalfinance.png', 'talento@globalfinance.es', '+34 913 456 789', true, 1200, 1995, false, true),
(6, 'Inversa Capital', 'FINANCE', 'Gestión de patrimonios y planificación financiera.', 'Barcelona, España', 'https://inversacapital.es', 'https://example.com/logos/inversa.png', 'empleo@inversacapital.es', '+34 933 567 890', true, 300, 2008, true, true),
(7, 'Constructora del Sur', 'CONSTRUCTION', 'Edificación residencial y obra civil.', 'Sevilla, España', 'https://constructorasur.es', 'https://example.com/logos/construtora.png', 'obras@constructorasur.es', '+34 955 678 901', true, 600, 1988, false, false),
(8, 'Arquitectura XXI', 'CONSTRUCTION', 'Estudio de arquitectura y diseño de interiores.', 'Madrid, España', 'https://arquitecturaxxi.es', 'https://example.com/logos/arquitectura.png', 'estudio@arquitecturaxxi.es', '+34 914 567 890', true, 80, 2015, true, true),
(9, 'EduLearn Academy', 'EDUCATION', 'Plataforma de formación online y cursos profesionales.', 'Valencia, España', 'https://edulearn.es', 'https://example.com/logos/edulearn.png', 'info@edulearn.es', '+34 964 567 890', true, 120, 2016, true, true),
(10, 'Idiomas Sin Fronteras', 'EDUCATION', 'Academia de idiomas y cursos de inmersión lingüística.', 'Barcelona, España', 'https://idiomassinfronteras.es', 'https://example.com/logos/idiomas.png', 'cursos@idiomassinfronteras.es', '+34 934 678 901', true, 60, 2010, false, true),
(11, 'Creativos Asociados', 'CREATIVE', 'Agencia de publicidad y marketing digital.', 'Madrid, España', 'https://creativosasociados.es', 'https://example.com/logos/creativos.png', 'creativos@creativosasociados.es', '+34 915 678 901', true, 90, 2013, true, true),
(12, 'Estudio Visual', 'CREATIVE', 'Producción audiovisual y diseño gráfico.', 'Barcelona, España', 'https://estudiovisual.es', 'https://example.com/logos/visual.png', 'info@estudiovisual.es', '+34 935 678 901', true, 40, 2018, true, true),
(13, 'Solidaridad Social', 'SOCIAL', 'ONG de apoyo a colectivos vulnerables.', 'Madrid, España', 'https://solidaridadsocial.es', 'https://example.com/logos/solidaridad.png', 'voluntariado@solidaridadsocial.es', '+34 916 789 012', true, 50, 2000, false, true),
(14, 'Inclusión Activa', 'SOCIAL', 'Centro de inserción laboral para personas con discapacidad.', 'Sevilla, España', 'https://inclusionactiva.es', 'https://example.com/logos/inclusion.png', 'info@inclusionactiva.es', '+34 956 789 012', true, 30, 2015, false, true),
(15, 'Science Lab Research', 'SCIENCE', 'Laboratorio de investigación biotecnológica.', 'Granada, España', 'https://sciencelab.es', 'https://example.com/logos/sciencelab.png', 'lab@sciencelab.es', '+34 958 789 012', true, 45, 2012, false, true),
(16, 'BioTech Innovations', 'SCIENCE', 'Desarrollo de soluciones biotecnológicas avanzadas.', 'Barcelona, España', 'https://biotechinnovations.es', 'https://example.com/logos/biotech.png', 'rrhh@biotechinnovations.es', '+34 936 789 012', true, 70, 2014, false, true),
(17, 'Hostelería del Sol', 'HOSPITALITY', 'Cadena de hoteles y restaurantes.', 'Málaga, España', 'https://hosteleriadelsol.es', 'https://example.com/logos/hosteleria.png', 'empleo@hosteleriadelsol.es', '+34 952 789 012', true, 350, 1985, false, true),
(18, 'Gourmet Experience', 'HOSPITALITY', 'Grupo de restauración y eventos gastronómicos.', 'Madrid, España', 'https://gourmetexperience.es', 'https://example.com/logos/gourmet.png', 'rrhh@gourmetexperience.es', '+34 917 890 123', true, 180, 2008, false, true),
(19, 'Deporte Total', 'SPORTS', 'Gestión de instalaciones deportivas y eventos.', 'Madrid, España', 'https://deportetotal.es', 'https://example.com/logos/deporte.png', 'info@deportetotal.es', '+34 918 901 234', true, 120, 2010, false, true),
(20, 'Fitness & Health', 'SPORTS', 'Cadena de gimnasios y centros deportivos.', 'Barcelona, España', 'https://fitnesshealth.es', 'https://example.com/logos/fitness.png', 'empleo@fitnesshealth.es', '+34 937 890 123', true, 200, 2012, false, true),
(21, 'Arte y Cultura', 'ARTS', 'Galería de arte y gestión cultural.', 'Madrid, España', 'https://arteycultura.es', 'https://example.com/logos/arte.png', 'info@arteycultura.es', '+34 919 012 345', true, 25, 2015, true, true),
(22, 'Estudio Creativo', 'ARTS', 'Taller de arte y diseño de autor.', 'Valencia, España', 'https://estudiocreativo.es', 'https://example.com/logos/estudio.png', 'arte@estudiocreativo.es', '+34 965 890 123', true, 12, 2018, true, true),
(23, 'StudentJob España', 'OTHER', 'Plataforma de empleo para estudiantes y jóvenes.', 'Madrid, España', 'https://studentjob.es', 'https://example.com/logos/studentjob.png', 'info@studentjob.es', '+34 911 234 567', true, 25, 2015, true, true),
(24, 'Media Jornada Empleo', 'OTHER', 'Bolsa de empleo especializada en trabajos de media jornada.', 'Barcelona, España', 'https://mediajornadaempleo.es', 'https://example.com/logos/mediajornada.png', 'rrhh@mediajornadaempleo.es', '+34 932 345 678', true, 18, 2018, true, true),
(25, 'Trabajos Universitarios', 'OTHER', 'Portal de empleo exclusivo para universitarios.', 'Valencia, España', 'https://trabajosuniversitarios.es', 'https://example.com/logos/trabajosuni.png', 'info@trabajosuniversitarios.es', '+34 963 456 789', true, 15, 2019, true, true),
(26, 'Estudiantes en Prácticas', 'OTHER', 'Agencia de colocación de prácticas profesionales.', 'Sevilla, España', 'https://estudiantesenpracticas.es', 'https://example.com/logos/estudiantespracticas.png', 'empleo@estudiantesenpracticas.es', '+34 954 567 890', true, 12, 2020, true, true),
(27, 'Media Jornada Hostelería', 'OTHER', 'Especialistas en contratación de estudiantes para hostelería.', 'Málaga, España', 'https://mediajornadahosteleria.es', 'https://example.com/logos/hosteleriamedia.png', 'rrhh@mediajornadahosteleria.es', '+34 952 678 901', true, 20, 2017, false, true),
(28, 'Student Retail Jobs', 'OTHER', 'Empleos de fin de semana y media jornada en tiendas.', 'Madrid, España', 'https://studentretailjobs.es', 'https://example.com/logos/retailstudent.png', 'info@studentretailjobs.es', '+34 915 789 012', true, 30, 2016, false, true),
(29, 'Trabajos Flexibles', 'OTHER', 'Bolsa de trabajo flexible para estudiantes.', 'Bilbao, España', 'https://trabajosflexibles.es', 'https://example.com/logos/flexibles.png', 'empleo@trabajosflexibles.es', '+34 944 890 123', true, 14, 2021, true, true),
(30, 'Campus Trabajo', 'OTHER', 'Portal de empleo para estudiantes universitarios.', 'Zaragoza, España', 'https://campustrabajo.es', 'https://example.com/logos/campustrabajo.png', 'info@campustrabajo.es', '+34 976 901 234', true, 10, 2022, true, true);

-- ============================================
-- 2. JOB POSITIONS
-- ============================================
INSERT INTO job_positions (id, title, level, description, category, company_id, active, career_path) VALUES
(1, 'Desarrollador Full Stack', 'JUNIOR', 'Desarrollo de aplicaciones web con React y Spring Boot', 'TECHNOLOGY', 1, true, 'TECHNOLOGY'),
(2, 'Desarrollador Senior', 'SENIOR', 'Liderazgo técnico y arquitectura de soluciones', 'TECHNOLOGY', 1, true, 'TECHNOLOGY'),
(3, 'Data Scientist', 'SEMI_SENIOR', 'Análisis de datos y modelos predictivos', 'TECHNOLOGY', 2, true, 'TECHNOLOGY'),
(4, 'Médico General', 'SENIOR', 'Atención primaria y consulta médica', 'HEALTH', 3, true, 'HEALTH'),
(5, 'Enfermero', 'JUNIOR', 'Cuidado de pacientes y asistencia médica', 'HEALTH', 3, true, 'HEALTH'),
(6, 'Fisioterapeuta', 'JUNIOR', 'Rehabilitación y terapia física', 'HEALTH', 4, true, 'HEALTH'),
(7, 'Asesor Financiero', 'JUNIOR', 'Asesoramiento a clientes y gestión de carteras', 'FINANCE', 5, true, 'BUSINESS'),
(8, 'Analista de Riesgos', 'SEMI_SENIOR', 'Evaluación y gestión de riesgos financieros', 'FINANCE', 5, true, 'BUSINESS'),
(9, 'Gestor de Patrimonios', 'SENIOR', 'Planificación financiera y gestión de inversiones', 'FINANCE', 6, true, 'BUSINESS'),
(10, 'Ingeniero de Obra', 'SEMI_SENIOR', 'Supervisión de obras y gestión de proyectos', 'CONSTRUCTION', 7, true, 'CONSTRUCTION'),
(11, 'Arquitecto', 'SENIOR', 'Diseño y planificación de proyectos arquitectónicos', 'CONSTRUCTION', 8, true, 'CONSTRUCTION'),
(12, 'Diseñador de Interiores', 'JUNIOR', 'Diseño de espacios y selección de materiales', 'CREATIVE', 8, true, 'CREATIVE'),
(13, 'Profesor de Programación', 'JUNIOR', 'Impartición de cursos de desarrollo web', 'EDUCATION', 9, true, 'SOCIAL'),
(14, 'Profesor de Inglés', 'JUNIOR', 'Clases de inglés para adultos y empresas', 'EDUCATION', 10, true, 'SOCIAL'),
(15, 'Diseñador Gráfico', 'JUNIOR', 'Diseño de materiales visuales y branding', 'CREATIVE', 11, true, 'CREATIVE'),
(16, 'Editor de Video', 'JUNIOR', 'Edición y postproducción de contenido audiovisual', 'CREATIVE', 12, true, 'CREATIVE'),
(17, 'Trabajador Social', 'JUNIOR', 'Atención a colectivos vulnerables', 'SOCIAL', 13, true, 'SOCIAL'),
(18, 'Coordinador de Proyectos Sociales', 'SEMI_SENIOR', 'Gestión de proyectos de inclusión social', 'SOCIAL', 14, true, 'SOCIAL'),
(19, 'Técnico de Laboratorio', 'JUNIOR', 'Análisis y experimentación en laboratorio', 'SCIENCE', 15, true, 'SCIENCE'),
(20, 'Investigador', 'SENIOR', 'Investigación y desarrollo de proyectos científicos', 'SCIENCE', 16, true, 'SCIENCE'),
(21, 'Camarero', 'JUNIOR', 'Atención al cliente en restaurante', 'HOSPITALITY', 17, true, 'BUSINESS'),
(22, 'Cocinero', 'JUNIOR', 'Preparación de platos en cocina', 'HOSPITALITY', 17, true, 'BUSINESS'),
(23, 'Recepcionista', 'JUNIOR', 'Atención al público y gestión de reservas', 'HOSPITALITY', 18, true, 'BUSINESS'),
(24, 'Monitor Deportivo', 'JUNIOR', 'Coordinación de actividades deportivas', 'SPORTS', 19, true, 'SPORTS'),
(25, 'Entrenador Personal', 'SEMI_SENIOR', 'Entrenamiento personalizado y planes de ejercicio', 'SPORTS', 20, true, 'SPORTS'),
(26, 'Curador de Arte', 'SEMI_SENIOR', 'Gestión de exposiciones y colecciones artísticas', 'ARTS', 21, true, 'CREATIVE'),
(27, 'Artista Plástico', 'JUNIOR', 'Creación de obras de arte', 'ARTS', 22, true, 'CREATIVE'),
(28, 'Asesor de Empleo', 'JUNIOR', 'Orientación laboral para estudiantes', 'OTHER', 23, true, 'SOCIAL'),
(29, 'Técnico de Selección', 'JUNIOR', 'Procesos de selección para media jornada', 'OTHER', 24, true, 'BUSINESS'),
(30, 'Community Manager', 'JUNIOR', 'Gestión de redes sociales y contenido digital', 'OTHER', 25, true, 'CREATIVE'),
(31, 'Gestor de Prácticas', 'JUNIOR', 'Coordinación de programas de prácticas profesionales', 'OTHER', 26, true, 'SOCIAL'),
(32, 'Ayudante de Cocina', 'JUNIOR', 'Apoyo en cocina para media jornada', 'OTHER', 27, true, 'BUSINESS'),
(33, 'Dependiente', 'JUNIOR', 'Atención al cliente en tienda', 'OTHER', 28, true, 'BUSINESS'),
(34, 'Asistente Virtual', 'JUNIOR', 'Soporte administrativo remoto', 'OTHER', 29, true, 'BUSINESS'),
(35, 'Becario Universitario', 'INTERN', 'Prácticas en administración y gestión', 'OTHER', 30, true, 'BUSINESS');

-- ============================================
-- 3. JOB VACANCIES
-- ============================================
INSERT INTO job_vacancies (id, position_id, min_salary, max_salary, contract_type, work_modality, location, available_slots, weekly_hours, active, visa_sponsorship, opening_date) VALUES
(1, 1, 28000, 35000, 'FULL_TIME', 'HYBRID', 'Madrid, España', 3, 40, true, false, CURRENT_DATE),
(2, 2, 50000, 70000, 'FULL_TIME', 'REMOTE', 'Madrid, España', 2, 40, true, false, CURRENT_DATE),
(3, 3, 40000, 55000, 'FULL_TIME', 'HYBRID', 'Barcelona, España', 2, 40, true, false, CURRENT_DATE),
(4, 4, 60000, 80000, 'FULL_TIME', 'ONSITE', 'Valencia, España', 2, 40, true, false, CURRENT_DATE),
(5, 5, 28000, 35000, 'FULL_TIME', 'ONSITE', 'Valencia, España', 5, 40, true, false, CURRENT_DATE),
(6, 6, 30000, 40000, 'FULL_TIME', 'ONSITE', 'Sevilla, España', 3, 40, true, false, CURRENT_DATE),
(7, 7, 32000, 42000, 'FULL_TIME', 'ONSITE', 'Madrid, España', 4, 40, true, false, CURRENT_DATE),
(8, 8, 45000, 60000, 'FULL_TIME', 'HYBRID', 'Madrid, España', 2, 40, true, false, CURRENT_DATE),
(9, 9, 55000, 75000, 'FULL_TIME', 'HYBRID', 'Barcelona, España', 1, 40, true, false, CURRENT_DATE),
(10, 10, 40000, 55000, 'FULL_TIME', 'ONSITE', 'Sevilla, España', 2, 40, true, false, CURRENT_DATE),
(11, 11, 45000, 60000, 'FULL_TIME', 'HYBRID', 'Madrid, España', 2, 40, true, false, CURRENT_DATE),
(12, 12, 26000, 34000, 'FULL_TIME', 'REMOTE', 'Madrid, España', 3, 40, true, false, CURRENT_DATE),
(13, 13, 28000, 36000, 'FULL_TIME', 'REMOTE', 'Valencia, España', 3, 40, true, false, CURRENT_DATE),
(14, 14, 25000, 32000, 'FULL_TIME', 'ONSITE', 'Barcelona, España', 4, 40, true, false, CURRENT_DATE),
(15, 15, 26000, 34000, 'FULL_TIME', 'REMOTE', 'Madrid, España', 3, 40, true, false, CURRENT_DATE),
(16, 16, 26000, 34000, 'FULL_TIME', 'HYBRID', 'Barcelona, España', 2, 40, true, false, CURRENT_DATE),
(17, 17, 26000, 34000, 'FULL_TIME', 'ONSITE', 'Madrid, España', 3, 40, true, false, CURRENT_DATE),
(18, 18, 32000, 42000, 'FULL_TIME', 'HYBRID', 'Sevilla, España', 2, 40, true, false, CURRENT_DATE),
(19, 19, 24000, 30000, 'FULL_TIME', 'ONSITE', 'Granada, España', 3, 40, true, false, CURRENT_DATE),
(20, 20, 40000, 55000, 'FULL_TIME', 'ONSITE', 'Barcelona, España', 2, 40, true, false, CURRENT_DATE),
(21, 21, 18000, 24000, 'PART_TIME', 'ONSITE', 'Málaga, España', 6, 20, true, false, CURRENT_DATE),
(22, 22, 20000, 28000, 'FULL_TIME', 'ONSITE', 'Málaga, España', 4, 40, true, false, CURRENT_DATE),
(23, 23, 19000, 25000, 'FULL_TIME', 'ONSITE', 'Madrid, España', 4, 40, true, false, CURRENT_DATE),
(24, 24, 20000, 28000, 'PART_TIME', 'ONSITE', 'Madrid, España', 4, 20, true, false, CURRENT_DATE),
(25, 25, 30000, 40000, 'FULL_TIME', 'HYBRID', 'Barcelona, España', 2, 40, true, false, CURRENT_DATE),
(26, 26, 30000, 40000, 'FULL_TIME', 'ONSITE', 'Madrid, España', 1, 40, true, false, CURRENT_DATE),
(27, 27, 24000, 32000, 'PART_TIME', 'REMOTE', 'Valencia, España', 2, 20, true, false, CURRENT_DATE),
(28, 28, 22000, 30000, 'FULL_TIME', 'REMOTE', 'Madrid, España', 3, 40, true, false, CURRENT_DATE),
(29, 29, 22000, 30000, 'FULL_TIME', 'REMOTE', 'Barcelona, España', 3, 40, true, false, CURRENT_DATE),
(30, 30, 24000, 32000, 'FULL_TIME', 'REMOTE', 'Madrid, España', 2, 40, true, false, CURRENT_DATE),
(31, 31, 24000, 32000, 'FULL_TIME', 'HYBRID', 'Sevilla, España', 2, 40, true, false, CURRENT_DATE),
(32, 32, 18000, 24000, 'PART_TIME', 'ONSITE', 'Málaga, España', 4, 20, true, false, CURRENT_DATE),
(33, 33, 19000, 25000, 'PART_TIME', 'ONSITE', 'Madrid, España', 5, 20, true, false, CURRENT_DATE),
(34, 34, 20000, 28000, 'PART_TIME', 'REMOTE', 'Bilbao, España', 3, 20, true, false, CURRENT_DATE),
(35, 35, 18000, 24000, 'INTERNSHIP', 'HYBRID', 'Zaragoza, España', 4, 20, true, false, CURRENT_DATE);

-- ============================================
-- 4. JOB REQUIREMENTS
-- ============================================
INSERT INTO job_requirements (vacancy_id, type, skill_key, min_value, mandatory) VALUES
(1, 'SKILL', 'basic_programming', 2, true),
(1, 'SKILL', 'logic_thinking', 1, true),
(1, 'STAT', 'intelligence', 30, true),
(1, 'EDUCATION', 'high_school', 1, true),
(2, 'SKILL', 'advanced_programming', 3, true),
(2, 'SKILL', 'java_advanced', 2, true),
(2, 'EXPERIENCE_YEARS', 'experience', 3, true),
(2, 'STAT', 'intelligence', 50, true),
(3, 'SKILL', 'data_analysis', 2, true),
(3, 'SKILL', 'statistics', 2, true),
(3, 'STAT', 'intelligence', 40, true),
(4, 'SKILL', 'medical_diagnostics', 3, true),
(4, 'EDUCATION', 'university', 1, true),
(4, 'EXPERIENCE_YEARS', 'experience', 2, true),
(5, 'SKILL', 'nursing_basics', 2, true),
(5, 'SKILL', 'first_aid', 2, true),
(5, 'EDUCATION', 'vocational', 1, true),
(6, 'SKILL', 'physiotherapy_basics', 2, true),
(6, 'SKILL', 'rehabilitation', 1, true),
(6, 'EDUCATION', 'vocational', 1, true),
(7, 'SKILL', 'financial_other', 2, true),
(7, 'STAT', 'charisma', 30, true),
(7, 'EDUCATION', 'high_school', 1, true),
(8, 'SKILL', 'statistics', 3, true),
(8, 'SKILL', 'big_data', 2, true),
(8, 'EDUCATION', 'university', 1, true),
(9, 'SKILL', 'business_strategy', 3, true),
(9, 'SKILL', 'negotiation', 3, true),
(9, 'EXPERIENCE_YEARS', 'experience', 5, true),
(10, 'SKILL', 'construction_basics', 3, true),
(10, 'SKILL', 'blueprint_reading', 2, true),
(10, 'EXPERIENCE_YEARS', 'experience', 2, true),
(11, 'SKILL', 'technical_drawing', 3, true),
(11, 'SKILL', 'project_management', 2, true),
(11, 'EDUCATION', 'university', 1, true),
(12, 'SKILL', 'interior_design', 2, true),
(12, 'SKILL', 'basic_graphic_design', 1, true),
(12, 'STAT', 'creativity', 30, true),
(13, 'SKILL', 'basic_programming', 2, true),
(13, 'SKILL', 'communication', 2, true),
(13, 'EDUCATION', 'high_school', 1, true),
(14, 'SKILL', 'languages', 3, true),
(14, 'SKILL', 'communication', 2, true),
(14, 'EDUCATION', 'high_school', 1, true),
(15, 'SKILL', 'basic_graphic_design', 2, true),
(15, 'STAT', 'creativity', 30, true),
(16, 'SKILL', 'video_editing', 2, true),
(16, 'SKILL', 'creative_writing', 1, true),
(17, 'SKILL', 'communication', 2, true),
(17, 'SKILL', 'community_work_basic', 1, true),
(18, 'SKILL', 'project_management', 2, true),
(18, 'SKILL', 'leadership', 2, true),
(18, 'EXPERIENCE_YEARS', 'experience', 2, true),
(19, 'SKILL', 'basic_chemistry', 2, true),
(19, 'SKILL', 'lab_techniques', 1, true),
(20, 'SKILL', 'research_methods', 3, true),
(20, 'EDUCATION', 'university', 1, true),
(21, 'SKILL', 'customer_service', 2, true),
(22, 'SKILL', 'basic_cooking', 2, true),
(23, 'SKILL', 'customer_service', 2, true),
(23, 'SKILL', 'communication', 1, true),
(24, 'SKILL', 'sports', 2, true),
(24, 'SKILL', 'teamwork', 2, true),
(25, 'SKILL', 'fitness', 3, true),
(25, 'SKILL', 'leadership', 2, true),
(26, 'SKILL', 'art', 3, true),
(26, 'SKILL', 'management', 2, true),
(27, 'SKILL', 'art', 2, true),
(27, 'STAT', 'creativity', 40, true),
(28, 'SKILL', 'communication', 2, true),
(28, 'SKILL', 'counseling_skills', 1, true),
(29, 'SKILL', 'recruitment', 2, true),
(29, 'SKILL', 'communication', 2, true),
(30, 'SKILL', 'social_media_management', 2, true),
(30, 'SKILL', 'creative_writing', 2, true),
(31, 'SKILL', 'project_management', 2, true),
(31, 'SKILL', 'organization', 2, true),
(32, 'SKILL', 'basic_cooking', 1, true),
(33, 'SKILL', 'customer_service', 2, true),
(34, 'SKILL', 'office', 2, true),
(34, 'SKILL', 'communication', 2, true),
(35, 'SKILL', 'office', 1, false),
(35, 'EDUCATION', 'high_school', 1, false);

-- ============================================
-- 5. JOB EVENTS (con occurred_at para PostgreSQL)
-- ============================================
INSERT INTO job_events (type, title, description, salary_change, performance_change, satisfaction_change, stress_change, resolved, occurred_at) VALUES
('BONUS', '¡Bono por rendimiento!', 'Has superado las expectativas este mes. La empresa te reconoce con un bono económico.', 300, 10, 15, -5, false, CURRENT_TIMESTAMP),
('BONUS', 'Bono por objetivos', 'Has cumplido todos los objetivos del trimestre. ¡Buen trabajo!', 500, 15, 20, -10, false, CURRENT_TIMESTAMP),
('PROMOTION', '¡Ascenso!', 'Tu trabajo ha sido reconocido. Has sido ascendido a un puesto superior.', 400, 20, 25, 10, false, CURRENT_TIMESTAMP),
('PROMOTION', 'Cambio de rol', 'Te han ofrecido un nuevo rol con más responsabilidades y mejor salario.', 350, 15, 20, 15, false, CURRENT_TIMESTAMP),
('CONFLICT', 'Desacuerdo con compañero', 'Has tenido un conflicto con un compañero de trabajo por diferencias de opinión.', 0, -10, -15, 15, false, CURRENT_TIMESTAMP),
('CONFLICT', 'Problemas con el jefe', 'Has tenido un desencuentro con tu supervisor directo.', 0, -15, -20, 20, false, CURRENT_TIMESTAMP),
('PROJECT_SUCCESS', 'Proyecto exitoso', 'El proyecto en el que has trabajado ha sido un éxito rotundo.', 200, 15, 20, -10, false, CURRENT_TIMESTAMP),
('PROJECT_SUCCESS', 'Reconocimiento público', 'La dirección ha reconocido públicamente tu contribución al proyecto.', 0, 10, 25, -5, false, CURRENT_TIMESTAMP),
('PROJECT_FAILURE', 'Proyecto fallido', 'El proyecto no ha alcanzado los objetivos esperados.', 0, -15, -20, 15, false, CURRENT_TIMESTAMP),
('PROJECT_FAILURE', 'Retraso en la entrega', 'No se ha cumplido con la fecha de entrega del proyecto.', 0, -10, -15, 10, false, CURRENT_TIMESTAMP),
('BURNOUT', 'Agotamiento laboral', 'El exceso de trabajo está pasando factura a tu salud mental.', 0, -20, -25, 25, false, CURRENT_TIMESTAMP),
('BURNOUT', 'Necesitas un descanso', 'Llevas muchas horas trabajando sin descanso.', 0, -10, -10, 15, false, CURRENT_TIMESTAMP),
('OFFER_FROM_RIVAL', 'Oferta de la competencia', 'Una empresa rival te ha ofrecido un puesto con mejores condiciones.', 0, 0, 10, 5, false, CURRENT_TIMESTAMP),
('MENTOR_LEAVES', 'Tu mentor se va', 'La persona que te mentorizaba ha dejado la empresa.', 0, -10, -15, 10, false, CURRENT_TIMESTAMP),
('TEAM_RESTRUCTURE', 'Reestructuración del equipo', 'La empresa ha reorganizado los equipos.', 0, -5, -10, 15, false, CURRENT_TIMESTAMP),
('QUARTERLY_REVIEW', 'Revisión trimestral positiva', 'Tu evaluación trimestral ha sido excelente.', 200, 10, 15, -10, false, CURRENT_TIMESTAMP),
('QUARTERLY_REVIEW', 'Revisión trimestral negativa', 'Tu evaluación trimestral no ha sido buena.', 0, -10, -15, 15, false, CURRENT_TIMESTAMP),
('DEMOTION', 'Descenso de categoría', 'Por motivos organizativos, tu puesto ha sido reajustado a la baja.', -200, -15, -25, 20, false, CURRENT_TIMESTAMP);

-- ============================================
-- 6. MISSIONS
-- ============================================
INSERT INTO job_missions (title, description, difficulty, deadline_hours, xp_reward, salary_bonus, reputation_gain, skill_reward, completed) VALUES
('Completar informe mensual', 'Entrega el informe de resultados del departamento antes del plazo', 'EASY', 24, 50, 100, 5, 'productivity', false),
('Capacitar a nuevo empleado', 'Ayuda a integrar al nuevo compañero durante su primera semana', 'MEDIUM', 72, 100, 200, 10, 'leadership', false),
('Optimizar proceso de trabajo', 'Propón y aplica una mejora en los procesos del departamento', 'HARD', 120, 200, 500, 15, 'problem_solving', false),
('Proyecto trimestral', 'Lidera y completa el proyecto del trimestre con éxito', 'EPIC', 240, 500, 1000, 25, 'project_management', false),
('Resolver queja de cliente', 'Atiende y resuelve satisfactoriamente una queja importante', 'MEDIUM', 48, 75, 150, 8, 'negotiation', false),
('Documentar código', 'Documenta correctamente el código del último proyecto', 'EASY', 24, 40, 80, 4, 'communication', false),
('Presentación al cliente', 'Prepara y presenta una propuesta a un cliente potencial', 'HARD', 96, 180, 400, 12, 'charisma', false),
('Revisión de seguridad', 'Realiza una auditoría de seguridad del sistema', 'MEDIUM', 48, 90, 180, 7, 'cybersecurity_basics', false),
('Capacitación técnica', 'Completa un curso de capacitación técnica ofrecido por la empresa', 'MEDIUM', 72, 120, 0, 10, 'technical_skill', false),
('Organizar evento de equipo', 'Coordina una actividad de team building para el departamento', 'MEDIUM', 48, 80, 200, 15, 'teamwork', false),
('Cumplir objetivos trimestrales', 'Alcanza todos los objetivos marcados para el trimestre', 'HARD', 240, 300, 800, 20, 'ambition', false),
('Asistir a conferencia', 'Representa a la empresa en una conferencia del sector', 'MEDIUM', 48, 100, 300, 12, 'networking', false),
('Mejorar métricas del equipo', 'Ayuda a mejorar las métricas de rendimiento del equipo', 'HARD', 168, 250, 600, 18, 'leadership', false),
('Resolver bug crítico', 'Encuentra y soluciona un error crítico en producción', 'HARD', 24, 150, 300, 15, 'problem_solving', false),
('Redactar propuesta comercial', 'Elabora una propuesta comercial para un cliente potencial', 'MEDIUM', 72, 90, 200, 10, 'negotiation', false),
('Entrevistar candidato', 'Participa en el proceso de entrevista de un nuevo candidato', 'EASY', 24, 60, 0, 8, 'communication', false),
('Actualizar documentación', 'Revisa y actualiza toda la documentación del proyecto', 'EASY', 48, 50, 100, 5, 'organization', false),
('Desarrollar nueva funcionalidad', 'Implementa una nueva funcionalidad solicitada por el cliente', 'HARD', 120, 200, 500, 15, 'advanced_programming', false),
('Analizar competencia', 'Realiza un análisis detallado de la competencia', 'MEDIUM', 72, 100, 200, 10, 'data_analysis', false),
('Optimizar base de datos', 'Mejora el rendimiento de las consultas a la base de datos', 'HARD', 96, 180, 400, 12, 'sql', false);