## YAML Template.
---

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
  port:8080
  
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      cors-configurations:
        '[/**]':
          allowed-origins: "http://localhost:4200" # Solo uno, no múltiples orígenes
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
      routes:
      - id: user_full
        uri: lb://businessdomain-userservice
        predicates:
          - Path=/api/users/full/**
        filter:
          - AuthenticationFiltering

      - id: user_service
        uri: lb://businessdomain-userservice
        predicates:
        - Path=/api/users/**

      - id: person_service
        uri: lb://businessdomain-personservice
        predicates:
        - Path=/api/characters/**

      - id: system_service
        uri: lb://businessdomain-systemservice
        predicates:
          - Path=/api/systems/**

      - id: formation_service_formations
        uri: lb://businessdomain-formationservice
        predicates:
          - Path=/api/formations/**

      - id: formation_service_trainer
        uri: lb://businessdomain-formationservice
        predicates:
          - Path=/api/trainer/**

      - id: formation_service_trainer
        uri: lb://businessdomain-formationservice
        predicates:
          - Path=/api/scholarships/**

      - id: formation_service_trainer
        uri: lb://businessdomain-formationservice
        predicates:
          - Path=/api/exams/**

      - id: formation_service_trainer
        uri: lb://businessdomain-formationservice
        predicates:
          - Path=/api/character-exams/**

      - id: finances_service_trainer
        uri: lb://businessdomain-financeservice
        predicates:
          - Path=/api/accounts/**

      - id: finances_service_trainer
        uri: lb://businessdomain-financeservice
        predicates:
          - Path=/api/expenses/**

      - id: finances_service_trainer
        uri: lb://businessdomain-financeservice
        predicates:
          - Path=/api/incomes/**

      - id: finances_service_trainer
        uri: lb://businessdomain-financeservice
        predicates:
          - Path=/api/transactions/**

      - id: jobs_service_trainer
        uri: lb://businessdomain-jobservice
        predicates:
          - Path=/api/character-jobs/**

      - id: jobs_service_trainer
        uri: lb://businessdomain-jobservice
        predicates:
          - Path=/api/companies/**

      - id: jobs_service_trainer
        uri: lb://businessdomain-jobservice
        predicates:
          - Path=/api/job-positions/**

      - id: jobs_service_trainer
        uri: lb://businessdomain-jobservice
        predicates:
          - Path=/api/job-applications/**

      - id: jobs_service_trainer
        uri: lb://businessdomain-jobservice
        predicates:
          - Path=/api/job-events/**

      - id: jobs_service_trainer
        uri: lb://businessdomain-jobservice
        predicates:
          - Path=/api/job-vacancies/**

      - id: jobs_service_trainer
        uri: lb://businessdomain-jobservice
        predicates:
          - Path=/api/work-relationships/**

      - id: products_service_trainer
        uri: lb://businessdomain-productservice
        predicates:
          - Path=/api/products/**

      - id: products_service_trainer
        uri: lb://businessdomain-productservice
        predicates:
          - Path=/api/inventory/**

      - id: notification_service
        uri: lb://businessdomain-notificationservice
        predicates:
          - Path=/api/notifications/**

      - id: event_service_mission_templates
        uri: lb://businessdomain-eventservice
        predicates:
          - Path=/api/events/**

      - id: event_service_event_templates
        uri: lb://businessdomain-eventservice
        predicates:
          - Path=/api/missions/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG